name: Build NGINX Official (OpenSSL)

on:
  workflow_dispatch:

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev git

      - name: Download Nginx source
        run: |
          cd ..
          git clone --no-checkout https://github.com/nginx/nginx.git
          cd nginx
          git fetch --depth=1 origin refs/tags/release-1.29.0:refs/tags/release-1.29.0
          git checkout tags/release-1.29.0
      
      - name: Download openssl ssl
        run: |
          cd ..
          git clone --no-checkout https://github.com/openssl/openssl.git
          cd openssl
          git fetch --depth=1 origin refs/tags/openssl-3.5.2:refs/tags/openssl-3.5.2
          git checkout tags/openssl-3.5.2
          
      - name: Configure and build Nginx with module
        run: |
          cd ../nginx
          auto/configure --prefix=/usr/local/nginx --with-compat --with-http_v2_module \
            --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module \
            --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module \
            --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module \
            --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module \
            --with-http_v3_module --with-stream --with-stream_realip_module --with-stream_ssl_module \
            --with-stream_ssl_preread_module \
            --with-openssl=../openssl \
            --with-openssl-opt="enable-ktls"
          make -j$(nproc)
          sudo make install

      - name: Verify Nginx version
        run: /usr/local/nginx/sbin/nginx -V

      - name: Package Nginx binary
        run: |
          cd /usr/local/nginx
          sudo tar -czvf nginx-built.tar.gz sbin/ conf/ html/ logs/
          sudo chown runner:runner nginx-built.tar.gz
          sudo mv nginx-built.tar.gz $GITHUB_WORKSPACE
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: official-output
          path: nginx-built.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: official-output
          draft: false
          prerelease: false
          files: nginx-built.tar.gz
